// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZHzCXRdU7CGQBGj0nT_qNgcUmO4lRDc',
    appId: '1:695450420229:web:efc1618c1dc2a0d5d6c86c',
    messagingSenderId: '695450420229',
    projectId: 'chat-app-9d3d8',
    authDomain: 'chat-app-9d3d8.firebaseapp.com',
    storageBucket: 'chat-app-9d3d8.firebasestorage.app',
    measurementId: 'G-KNB9XRC4WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAct0cQcIf1dn6qBNz4asSCU3kLNZTIGJM',
    appId: '1:695450420229:android:242815aff17d7c69d6c86c',
    messagingSenderId: '695450420229',
    projectId: 'chat-app-9d3d8',
    storageBucket: 'chat-app-9d3d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKe0O7MF75U4n6jtgpDEjVfXCejX1YwPI',
    appId: '1:695450420229:ios:b888d88faa422c0fd6c86c',
    messagingSenderId: '695450420229',
    projectId: 'chat-app-9d3d8',
    storageBucket: 'chat-app-9d3d8.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

}